version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      - POSTGRES_USER=radix_user
      - POSTGRES_PASSWORD=radix
      - POSTGRES_DB=sensor_data
    ports:
      - "5454:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U radix_user -d sensor_data"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: . 
    command: bash -c "pip install --no-cache-dir -r requirements.txt && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://radix_user:radix@timescaledb:5432/sensor_data
    volumes:
      - .:/app 

volumes:
  timescale_data:
